# Generated by Django 5.2 on 2025-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=250)),
                ('Ingredients', models.CharField(max_length=555)),
                ('calories', models.IntegerField()),
                ('Protien', models.IntegerField()),
                ('Fiber', models.IntegerField()),
            ],
        ),
    ]
