# Generated by Django 5.2 on 2025-05-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_healthyfoods_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
       
        migrations.AddField(
            model_name='healthyfoods',
            name='collection',
            field=models.ManyToManyField(to='main_app.collection'),
        ),
    ]
