# Generated by Django 5.2 on 2025-05-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_healthyfoods_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthyfoods',
            name='image_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
