# Generated by Django 5.2 on 2025-05-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_collection_healthyfoods_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthyfoods',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.collection'),
        ),
    ]
