# Generated by Django 5.2 on 2025-05-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_healthyfoods_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='healthyDrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('drinkname', models.CharField(max_length=250)),
                ('calories', models.IntegerField()),
                ('Protien', models.IntegerField()),
                ('Ingredients', models.TextField(max_length=555)),
            ],
        ),
    ]
