# Generated by Django 5.2 on 2025-05-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_healthydrinks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthydrinks',
            name='user',
        ),
    ]
